Fix build on Python3.11+
The code was currently using method 6 [^1], however as the documentation
warns that will fail if the imported module depends on any packages that
need to be installed (the build system is about to discover what
packages need to be installed, so setup.py cannot require them to be
present!)
```
       File "/tmp/pip-build-env-o55qpsst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-o55qpsst/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/var/home/edwin/git/spacy_conll/spacy_conll/__init__.py", line 3, in <module>
          from .formatter import ConllFormatter
        File "/var/home/edwin/git/spacy_conll/spacy_conll/formatter.py", line 5, in <module>
          from spacy.language import Language
      ModuleNotFoundError: No module named 'spacy'

```

Use method 1, with setup.cfg instead and require setuptools >=  46.4.0

Also add minimal PEP-517 compatibility in `pyproject.toml` [^2].

Tested with: `python3 -m build .`

[1]: https://packaging.python.org/en/latest/guides/single-sourcing-package-version/
[2]: https://setuptools.pypa.io/en/latest/build_meta.html#how-to-use-it

Signed-off-by: Edwin Török <edwin@etorok.net>